### ISSUE TITLE
Ajouter une protection contre les doubles clics à la création d'une demande

### ISSUE THREAD

**Issue by monbocal** [betagouv/aplus#166]
Dans la plateforme, en tant qu'aidant, si je double clique sur "Envoyer ma demande", alors deux demandes sont créées. Est ce qu'un système de protection est envisageable ?

**Comment by jdauphant** [comment]
Oui, il le faudrait sur l'envoi de la réponse aussi

**Comment by jdauphant** [comment]
C'est fait ;)
