### ISSUE TITLE
Option "Répondre et clore" ?

### ISSUE THREAD

**Issue by monbocal** [betagouv/aplus#170]
Actuellement en train de gérer le flux des demandes encore ouvertes à fermer, une option "Répondre et clore" permettrait de gagner en fluidité dans l'outil, à la manière de ce qui est proposé sur Github.

Actuellement, je répond à une demande, je suis balancé sur la page toutes les demandes, je dois retrouver la demande que je suis en train de traiter pour l'ouvrir et la clore.

**Comment by jdauphant** [comment]
Ok, la clôture par l'expert est normalement exceptionnel (l'agent ne peut pas clôturer, seul un aidant ou l'expert peuvent le faire).
