### ISSUE TITLE
Sur Codacy : Prohibit using isDefined on optional types

### ISSUE THREAD

**Issue by jdauphant** [betagouv/aplus#534]
![image](https://user-images.githubusercontent.com/1238254/75803238-6b8ebb00-5d7e-11ea-9b18-31640a66e352.png)

La régle "Prohibit using isDefined on optional types" me semble pas pertinente, un avis ? on la supprime ?

**Comment by niladic** [comment]
Bah cette règle serait pertinente si `Option` `fold` inférait correctement les types en scala, mais c'est pas le cas :(
Typiquement ici ce serait plus clean d'écrire :
```scala
    request.session
          .get("userId")
          .orElse(request.queryString.get("token"))
          .orElse(request.queryString.get("key"))
          .fold(
             Ok(views.html.home())
           )(
             _ => TemporaryRedirect(
                s"${routes.ApplicationController.myApplications()}?${request.rawQueryString}"
             ) 
```
mais l'inférence est tellement mauvaise que le compilateur va t'inférer `Ok` et te lever une erreur comme quoi `TemporaryRedirect` n'est pas de type `Ok`... :(

Du coup, oui, supprime la règle, pas de pertinance due à la lib standard qui est pas top...

**Comment by jdauphant** [comment]
Ok
